package:
  name: pocketoptionapi
  version: 1.0.0

source:
  # Use the GitHub repository as the source
  git_url: https://github.com/honza-toegel/PocketOptionAPI
  git_branch: main  # Replace with the appropriate tag or branch
  #path: . #Enable instead of git_url and git_branch for a local conda-build without cloning from repo

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.1
    - pip
  run:
    - python >=3.1
    - numpy >=1.26.4
    - pandas >=2.2.2
    - requests >=2.32.3
    - anyio >=4.6.2
    - numexpr >=2.10.1
    - bottleneck >=1.4.2
    - pytz >=2024.1
    - tzlocal >=5.2
    - websockets >=10.4
    - typing_extensions >=4.11.0
    - urllib3 >=2.2.3
    - python-dateutil >=2.9.0

test:
  commands:
    - python -c "import pocketoptionapi"  # Replace with actual test commands if available

about:
  home: https://github.com/honza-toegel/PocketOptionAPI
  license: MIT
  license_family: MIT
  summary: "Pocket Options API - A Python API for PocketOption"
  description: |
    A Python API for interacting with PocketOption, designed to be simple and effective.

extra:
  recipe-maintainers:
    - your-github-username  # Replace with the actual maintainer's GitHub username
